print("Hugging Face Space Uploader for Todo Backend")
print("="*50)
print("There was an issue with the token provided.")
print()
print("To properly upload your backend files to: https://waseem4100-todoapi2.hf.space")
print()
print("Please follow these steps to get a valid token:")
print("1. Go to https://huggingface.co/settings/tokens")
print("2. Click on 'New token'")
print("3. Give it a name (e.g., 'todo-api-upload')")
print("4. Select 'Write' role for uploading files")
print("5. Copy the generated token")
print()
print("IMPORTANT: The token you previously provided may have been invalid or expired.")
print()
print("After getting a new token, you can run the upload using one of these methods:")
print()
print("Method 1: Set environment variable and run the upload script")
print("   On Windows Command Prompt: set HF_TOKEN=your_new_token_here")
print("   Then run: python upload_backend_with_env.py")
print()
print("Method 2: Use the Hugging Face CLI directly")
print("   huggingface-cli login")
print("   huggingface-cli upload Waseem4100/todoAPI2 D:\\Coding\\hackathons\\todo-app\\backend . --repo-type space")
print()
print("Your backend code has been fixed to resolve the deployment error:")
print("- Removed unsupported 'ondelete' parameter from Field() in todo.py")
print("- This should prevent the TypeError that was occurring on startup")
print()
print("Once you have a valid token, please try uploading again using one of the methods above.")